services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true

  esphome:
    image: esphome/esphome
    volumes:
      - ./esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true

  nginx:
    image: nginx:latest
    depends_on:
      homeassistant:
        condition: service_started
      esphome:
        condition: service_started
      certbot2:
        condition: service_completed_successfully
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  certbot2:
    image: "infinityofspace/certbot_dns_duckdns:latest"
    container_name: "certbot_dns_duckdns"
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/logs:/var/log/letsencrypt/:rw
    command: certonly
      --non-interactive
      --agree-tos
      --email $DNS_SUPPORT_EMAIL
      --preferred-challenges dns
      --authenticator dns-duckdns
      --dns-duckdns-token ${DUCKDNS_TOKEN}
      --dns-duckdns-propagation-seconds 30
      --domain $HASS_DOMAIN
      --domain $ESPHOME_DOMAIN
      # --dry-run


  # certbot:
  #   image: certbot/certbot:latest
  #   depends_on:
  #     - nginx
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw # this is where certbot will put the challeng files
  #     - ./certbot/conf/:/etc/letsencrypt/:rw # this is where certbot will put the certificates
  #     - ./certbot/logs:/var/log/letsencrypt/:rw
  #   profiles:
  #     - certbot