services:
  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    # network_mode: host
    # ports:
    #   - "8123:8123"
  esphome:
    image: esphome/esphome
    volumes:
      - ./esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    # network_mode: host
    ports:
      - "6052:6052"
      # - "6053:6053"
      # - "6054:6054"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw # this is where certbot will put the challeng files
      - ./certbot/conf/:/etc/letsencrypt/:rw # this is where certbot will put the certificates

  # certbot:
  #   image: certbot/certbot
  #   volumes:
  #     - ./certbot/www:/var/www/certbot
  #     - ./certbot/conf:/etc/letsencrypt
  #   command: certonly --webroot -w /var/www/certbot --force-renewal --email your-email@example.com -d yourdomain.com -d www.yourdomain.com
