services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true

  esphome:
    image: esphome/esphome
    volumes:
      - ./esphome/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true

  nginx:
    image: nginx:latest
    depends_on:
      - homeassistant
      - esphome
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/config/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    depends_on:
      - nginx
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw # this is where certbot will put the challeng files
      - ./certbot/conf/:/etc/letsencrypt/:rw # this is where certbot will put the certificates
    profiles:
      - certbot
